# Generated by Django 5.0.4 on 2024-04-18 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('Employee', 'Employee'), ('Project-Manager', 'Project-Manager'), ('Team-Leader', 'Team-Leader'), ('Admin', 'Admin')], max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('allocation_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('projectDescription', models.CharField(max_length=500)),
                ('project_assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectStartDate', models.DateField(default=models.DateTimeField(default=django.utils.timezone.now))),
                ('projectEndDate', models.DateField(null=True)),
                ('toDo', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.baseuser')),
            ],
        ),
    ]
